### ISSUE TITLE
ipv6 doesnt work?

### ISSUE THREAD

**Issue by buzztiaan** [DNotesCoin/DNotes#1]
Seems on a ipv6 enabled host this refuses to bind and open a RPC port

**Comment by DNotesCoin** [comment]
Hi Buzztiaan, 

I will get in touch with our networking guys. Would you provide some information about the issue you are having? Is it not finding peers? Not updating the blockchain?

**Comment by buzztiaan** [comment]
AddLocal([2001:470:xxxx::xxxx]:11223,1)
IPv6 eth0: 2001:470:xxxx::xxxx
ThreadRPCServer started
Error: An error occurred while setting up the RPC port 11223 for listening on IPv4: bind: Address already in use

**Comment by buzztiaan** [comment]
basically daemon starts, and directly kills itself
yet, no other daemon is running on that port whatsoever

**Comment by DNotesCoin** [comment]
Thank you. I will get back to you shortly once I reach out to our team. In the meantime, I did find this similar issue on bitcointalk that may provide some insight. https://bitcointalk.org/index.php?topic=624568.0

**Comment by buzztiaan** [comment]
Sorry, thats not a similar problem

**Comment by DNotesCoin** [comment]
Not in it's entirety, I was referring this part of the post. 
"If I put "listen=1" to any of the machines config file I always get:
Code:
Error: An error occurred while setting up the RPC port 19700 for listening on IPv4: bind: Address already in use"

**Comment by buzztiaan** [comment]
yeah , listen=1 is the parameter you set to enable the RPC port to be listening, which is indeed what i need

**Comment by buzztiaan** [comment]
is dnote by any chance based on bitcoin 0.7 code?

**Comment by DNotesCoin** [comment]
Litecoin fork, closer to .8 originally I believe.

**Comment by DNotesCoin** [comment]
Are you running a pool?

**Comment by jefs42** [comment]
Was trying to reproduce, enabled IPv6 on my Digital Ocean droplet, cloned and compiled the daemon. I already had a config and stuff from older work... Cleared the log and started up the daemon and got 

ThreadRPCServer started
send version message: version 1020000, blocks=307272, us=0.0.0.0:0, them=0.0.0.0:0, peer=127.0.0.1:0
sending: version (99 bytes)
AddLocal(107.170.0.36:11223,1)
IPv4 eth0: 107.170.0.36
AddLocal([2604:a880:0:1010::2eb3:2001]:11223,1)
IPv6 eth0: 2604:a880:0:1010::2eb3:2001
ThreadDNSAddressSeed started 

I was about to test sending remote RPC calls to both ipv4 and ipv6 addresses and noticed a difference. In my config file, the port for RPC is 11224 not 11223

rpcuser=*******
rpcpassword=*********************
port=11223
rpcport=11224
rpcallowip=*
daemon=1
debug=1
listen=1
server=1
gen=0
irc=0

Can you double check that you have different ports set for 'port' versus 'rpcport'? When I updated the config and changed rpcport also to 11223 and restarted the daemon I did indeed get the same error message as you mention - "ThreadRPCServer started
Error: An error occurred while setting up the RPC port 11223 for listening on IPv4: bind: Address already in use"

**Comment by DNotesCoin** [comment]
Hopefully that resolves the issue buzztiaan. Let us know if it worked out.

**Comment by buzztiaan** [comment]
i have no ports configured at all, its using the standards

small hint; see the -ipv6- address picked by my log snippet and its trying
to open a port on -ipv4- the next line ;)

**Comment by buzztiaan** [comment]
lol wow, in -3- years nobody -ever- tried to start this wallet with RPC enabled? amazing :rofl: 

ok, so the actual bug is, default rpc port is THE SAME as the default p2p port, which ofcourse would -never- work

**Comment by buzztiaan** [comment]
Pull req fixes it and works now..
Albeit IRC node discovery -and- DNS seeds are totally dead ..... next issue

**Comment by DNotesCoin** [comment]
Thanks! 

Yes, if I remember correctly we had setup 2 servers as DNS seeds as IRC was not reliable (and still isn't), which are currently no longer active. However, you can still setup up the conf and connect to main nodes. 
addnode=usdnotes.com
addnode=n6.dnotescoin.com
addnode=n7.dnotescoin.com
addnode=n4.dnotescoin.com
addnode=n5.dnotescoin.com
addnode=128.199.239.199
addnode=95.85.44.200
addnode=162.243.225.90

**Comment by DNotesCoin** [comment]
Also, please send me an email contact@dnotescoin.com buzztiaan.
